In [3]:
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

In [4]:
df=pd.read_csv("insurance.csv")

In [5]:
df

      age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]

In [6]:
df.isnull().sum()

age         0
sex         0
bmi         0
children    0
smoker      0
region      0
charges     0
dtype: int64

In [10]:
X=df.drop(columns=["charges","region"])
y=df["charges"]

In [12]:
X.head()

   age     sex     bmi  children smoker
0   19  female  27.900         0    yes
1   18    male  33.770         1     no
2   28    male  33.000         3     no
3   33    male  22.705         0     no
4   32    male  28.880         0     no

In [13]:
X["sex"]=X["sex"].map({"male":0,"female":1})

In [14]:
X["smoker"]=X["smoker"].map({"yes":1,"no":0})

In [16]:
X

      age  sex     bmi  children  smoker
0      19    1  27.900         0       1
1      18    0  33.770         1       0
2      28    0  33.000         3       0
3      33    0  22.705         0       0
4      32    0  28.880         0       0
...   ...  ...     ...       ...     ...
1333   50    0  30.970         3       0
1334   18    1  31.920         0       0
1335   18    1  36.850         0       0
1336   21    1  25.800         0       0
1337   61    1  29.070         0       1

[1338 rows x 5 columns]

In [24]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(
    X,y,test_size=0.2,random_state=42
)

In [25]:
from sklearn.linear_model import LinearRegression
model=LinearRegression()
model.fit(X_train,y_train)

LinearRegression()

In [26]:
y_pred=model.predict(X_test)

In [30]:
from sklearn.metrics import r2_score
r2=r2_score(y_test,y_pred)
print("r squired value is",r2)

r squired value is 0.7811302113434097

In [28]:
print("accuracy is :",r2*100)

accuracy is : 78.11302113434097